TRUNCATE TABLE brands CASCADE;
TRUNCATE TABLE cars CASCADE;
TRUNCATE TABLE categories CASCADE;
TRUNCATE TABLE engines CASCADE;
TRUNCATE TABLE models CASCADE;

ALTER SEQUENCE brands_seq RESTART WITH 1;
ALTER SEQUENCE cars_seq RESTART WITH 1;
ALTER SEQUENCE category_id_sequence RESTART WITH 1;
ALTER SEQUENCE engines_id_sequence RESTART WITH 1;
ALTER SEQUENCE model_id_sequence RESTART WITH 1;
